### ISSUE TITLE
./gradlew run --args="HelloSoot draw" hung at 75%.. is this the expected behavior.. pl. fix doc..

### ISSUE THREAD

**Issue by nagkumar** [noidsirius/SootTutorial#2]
This: r0
--------------
Units:
(1) r0 := @this: FizzBuzz
(2) i0 := @parameter0: int
(3) $i1 = i0 % 15
(4) if $i1 != 0 goto $i2 = i0 % 5
(5) $r4 = <java.lang.System: java.io.PrintStream out>
(6) virtualinvoke $r4.<java.io.PrintStream: void println(java.lang.String)>("FizzBuzz")
(7) goto [?= return]
(8) $i2 = i0 % 5
(9) if $i2 != 0 goto $i3 = i0 % 3
(10) $r3 = <java.lang.System: java.io.PrintStream out>
(11) virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>("Buzz")
(12) goto [?= return]
(13) $i3 = i0 % 3
(14) if $i3 != 0 goto $r1 = <java.lang.System: java.io.PrintStream out>
(15) $r2 = <java.lang.System: java.io.PrintStream out>
(16) virtualinvoke $r2.<java.io.PrintStream: void println(java.lang.String)>("Fizz")
(17) goto [?= return]
(18) $r1 = <java.lang.System: java.io.PrintStream out>
(19) virtualinvoke $r1.<java.io.PrintStream: void println(int)>(i0)
(20) return
--------------
Branch Statements:
if $i1 != 0 goto $i2 = i0 % 5
if $i2 != 0 goto $i3 = i0 % 3
if $i3 != 0 goto $r1 = <java.lang.System: java.io.PrintStream out>
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
<=========----> 75% EXECUTING [11m 52s].checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:233)
        at org.graphstream.ui.swingViewer.DefaultView.openInAFrame(DefaultView.java:214)
        at org.graphstream.ui.view.Viewer.addView(Viewer.java:505)
        at org.graphstream.ui.view.Viewer.addView(Viewer.java:483)
        at org.graphstream.graph.implementations.AbstractGraph.display(AbstractGraph.java:754)
        at org.graphstream.graph.implementations.AbstractGraph.display(AbstractGraph.java:747)
        at dev.navids.soottutorial.visual.Visualizer.draw(Visualizer.java:197)
        at dev.navids.soottutorial.hellosoot.HelloSoot.main(HelloSoot.java:72)
        at dev.navids.soottutorial.Main.main(Main.java:20)
<=========----> 75% EXECUTING [11m 14s]
> :run
<=========----> 75% EXECUTING [1m 7s]

doc fix needs https://github.com/noidsirius/SootTutorial

**Comment by nagkumar** [comment]
May be https://dev.to/darksmile92/run-gui-app-in-linux-docker-container-on-windows-host-4kde this also needs to be done, any case even after doing this, I am unable to see the graphics  tree as shown in  https://github.com/noidsirius/SootTutorial

**Comment by noidsirius** [comment]
It seems you provide a solution [here](https://github.com/noidsirius/SootTutorial/issues/3).
